inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - 'vendor/**/*'
    - 'bin/*'
    - config/initializers/devise.rb
    - 'spec/**/*.rb'
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
